# Generated by Django 5.2.18 on 2026-10-08 16:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='accounts.customerprofile', verbose_name='مشتری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shops.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قلم سبد خرید',
                'verbose_name_plural': 'اقلام سبد خرید',
                'constraints': [models.UniqueConstraint(fields=('customer', 'product'), name='unique_cart_item_per_customer'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cart_quantity_positive')],
            },
        ),
    ]
